### ISSUE TITLE
Review app not deployed automatically.

### ISSUE THREAD

**Issue by harry100** [danielstern/integration-test-repo-demo#4]
After I create a Pull Request, A new review app is created automatically but I need to deploy it manually from Heroku.
I get a 'This branch has not been deployed' message on my Pull Request.
After I manuall click create review app from heroku, I get a link to the review app.

Any help on this? Thanks

**Comment by harry100** [comment]
My app.json is the same as yours. @danielstern

**Comment by danielstern** [comment]
Hey Amanda.

Looks like a Heroku configuration issue.

I would make sure that Automatic Deployment is turned on.
With so many moving parts, it's also possible that the feature may be broken for a short period of time.

Cheers,
DS
________________________________
